name: Fast checks

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Audit dependencies
        run: "echo skipped-for-baseline-isolation"

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check the project
        run: |
          cargo check --workspace --all-targets --features blocking
          cargo check --workspace --all-targets --features bundled
          cargo check --workspace --all-targets --features indicatif
          cargo check --workspace --all-targets --features rustls
          cargo check --workspace --all-targets --features theseus
          cargo check --workspace --all-targets --features tokio
          cargo check --workspace --all-targets --features zonky
          cargo check --workspace --all-targets --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Check lints
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: "echo skipped-for-baseline-isolation"
  deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install cargo deny
        run: cargo install cargo-deny
      - name: Check licenses
        run: "echo skipped-for-baseline-isolation"

  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: "echo skipped-for-baseline-isolation"

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: "echo skipped-for-baseline-isolation"
